### ISSUE TITLE
uploadImage returns a permission denied

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaodjin-signup#42]
1/ Calling `uploadImage` in djaodjin-signup-vue.js results in a permission denied. This is due to an `$.ajax` call without authorization / csrf headers.

2/ `uploadImage` should use a dedicated API end-point name even if in some cases it will default to `djaodjinSettings.urls.user.api_contact` (Ex: `djaodjinSettings.urls.api.upload_profile_picture`).

3/ Reviewing the `#user-profile-container` widget, `updateProfile` is also not working in the presence of a profile picture because `saveProfileWithPicture` and `saveProfile` do not exist. In all cases, There should only be one `PATCH` request in `updateProfile`.

4/ Rename `uploadImage` to `uploadProfilePicture` to be more accurate.

**Comment by knivets** [comment]
As far as I've understood, two distinct templates (user contact and company profile) have been merged into one. Does this mean that we only deal with `Contact` and `Organization` (not `User`) models now? 

Some code for picture upload has been copy pasted from "profile-container". The current problem is that both controllers don't work when I try to upload a picture. When inspecting the issue more closely I've found that the `djaoapp/templates/saas/profile/index.html` is no longer using any Vue functionality when it comes to updating the data (since it uses `_form.html` template).

How should I approach solving this? Should I first convert the template to use Vue functionality? Converting a template means replacing `_form.html` with manually listed fields, which are not the same for distinct types of objects -- that means we need to use conditionals or maybe it makes sense to revert to using two distinct templates as we used to.

**Comment by smirolo** [comment]
Implementing [djaodjin-saas#222](https://github.com/djaodjin/djaodjin-saas/issues/222) will automatically solve the issue.
Improvement is to implement "2/ uploadImage should use a dedicated API end-point ..."

**Comment by knivets** [comment]
Could you provide the signatures for the endpoint?

**Comment by smirolo** [comment]
Completed in commit ca815635 and commit fe09f638.
